version: "3"

services:
  application:
    build: .
    container_name: "application"
    env_file: .env
    depends_on:
      - database
    volumes:
      - .:/app
    ports:
      - "3000:3000"
  database:
    container_name: "application_db"
    image: mysql:8
    env_file: .env
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3307:3306

