name: Test
on: pull_request

jobs:
  test:
    env:
      MYSQL_DATABASE: test_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root

    steps:
      - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.MYSQL_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: bundle install

      - name: Create database
        run: rake db:create

      - name: Run tests
        run: bin/rails tests


