name: Test
on: pull_request

jobs:
  test:

    runs-on: ubuntu-latest

    env:
      MYSQL_DATABASE: test_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root

    steps:
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -u${{ env.MYSQL_USER }} -p${{ env.MYSQL_PASSWORD }}

      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 2.7.0

      - name: Install dependencies
        run: bundle install

      - name: Create database
        run: rake db:setup

      - name: Run tests
        run: bin/rails test


